<?php

namespace AppBundle\Repository;

/**
 * LeagueTeamsMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueTeamsMatchRepository extends \Doctrine\ORM\EntityRepository
{
}
