<?php

namespace AppBundle\Repository;

/**
 * LeagueDoublesMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueDoublesMatchRepository extends \Doctrine\ORM\EntityRepository
{
}
