<?php

namespace AppBundle\Repository;

/**
 * LeagueRoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueRoundRepository extends \Doctrine\ORM\EntityRepository
{
}
