<?php

namespace AppBundle\Repository;

/**
 * LeagueGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
