<?php

namespace AppBundle\Repository;

/**
 * LeagueMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueMatchRepository extends \Doctrine\ORM\EntityRepository
{
}
