<?php

namespace AppBundle\Repository;

/**
 * SeasonStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
