<?php

namespace AppBundle\Repository;

/**
 * YearSeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearSeasonRepository extends \Doctrine\ORM\EntityRepository
{
}
